### ISSUE TITLE
Popular jobs content row not responsive at lower mobile resolutions (SE, SG-Fold)

### ISSUE THREAD

**Issue by liamdebellada** [TeamColony/colony#15]
# Steps to reproduce:
Change viewport width to value lower than 360px.

# Reproduced problem:
![image](https://user-images.githubusercontent.com/54673077/116829593-715b7880-ab9c-11eb-9a06-09a4c7727bb8.png)

**Comment by brunogrcsada** [comment]
![image](https://user-images.githubusercontent.com/54673205/117290446-ba921d80-ae65-11eb-975d-d31245ce36f0.png)
How's this for a change?

**Comment by liamdebellada** [comment]
Awesome, nice job!
